[package]
name = "miyagi"
version = "0.1.0"
edition = "2021"
categories = ["development-tools"]
homepage = "https://github.com/alextes/miyagi"
keywords = ["progress", "eta", "estimate"]
license = "MIT"
repository = "https://github.com/alextes/miyagi"
